export const BOTTLES = [
  { id: 'mionetto', name: 'Mionetto Sparkling (0%)' },
  { id: 'titos', name: "Tito's Vodka" },
  { id: 'blue_curacao', name: 'Blue Curaçao' },
  { id: 'st_germain', name: 'St-Germain Elderflower' },
  { id: 'cointreau', name: 'Cointreau Triple Sec' },
  { id: 'orange_bitters', name: 'Orange Bitters' },
  { id: 'lychee_juice', name: '100% Lychee Juice' },
];

export const RECIPES = [
  {
    id: '1',
    name: 'The Elderflower Spritz',
    isMocktail: true,
    ingredients: ['st_germain', 'mionetto'],
    spec: ['1.5 oz St-Germain', '3 oz Mionetto Alcohol-Removed Sparkling Wine', '1 oz Club Soda'],
    method: 'Build directly in a wine glass filled with fresh ice. Stir gently to integrate without losing carbonation.',
    glassware: 'Wine glass garnished with a lemon wheel and a slapped mint sprig',
  },
  {
    id: '2',
    name: 'The Cosmopolitan (Premium Spec)',
    isMocktail: false,
    ingredients: ['titos', 'cointreau'],
    spec: ["1.5 oz Tito's Handmade Vodka", '0.75 oz Cointreau', '0.75 oz Fresh Lime Juice', '0.5 oz Cranberry Juice Cocktail'],
    method: 'Combine all ingredients into a cocktail shaker with ice. Shake vigorously for 10-12 seconds and double strain.',
    glassware: 'Chilled coupe glass with an expressed orange peel',
  },
  {
    id: '3',
    name: 'The Azure Breeze',
    isMocktail: false,
    ingredients: ['titos', 'blue_curacao', 'orange_bitters'],
    spec: ["1.5 oz Tito's Handmade Vodka", '0.75 oz DeKuyper Blue Curaçao', '0.75 oz Fresh Lemon Juice', '0.5 oz Simple Syrup (1:1)', '2 dashes Angostura Orange Bitters'],
    method: 'Shake all ingredients well with ice, then strain into a rocks glass over fresh ice cubes.',
    glassware: 'Rocks glass garnished with a fresh lemon wheel',
  },
  {
    id: '4',
    name: 'Nectar of the Gods',
    isMocktail: false,
    ingredients: ['titos', 'st_germain', 'cointreau'],
    spec: ["1.5 oz Tito's Handmade Vodka", '0.75 oz St-Germain Elderflower Liqueur', '0.25 oz Cointreau', '0.5 oz Fresh Lemon Juice'],
    method: 'Add all ingredients to a shaker with ice. Shake hard to chill and aerate, then strain cleanly.',
    glassware: 'Chilled martini or coupe glass',
  },
  {
    id: '5',
    name: 'Blue Lagoon Mocktail',
    isMocktail: true,
    ingredients: ['blue_curacao'],
    spec: ['0.75 oz DeKuyper Blue Curaçao', '4 oz Premium Lemonade', 'Top with Lemon-Lime Soda'],
    method: 'Fill a highball glass with crushed ice. Pour in the ingredients, letting the blue color swirl, and stir gently.',
    glassware: 'Highball glass garnished with a maraschino cherry',
  },
  {
    id: '6',
    name: 'Citrus Starlight',
    isMocktail: true,
    ingredients: ['mionetto', 'st_germain', 'orange_bitters'],
    spec: ['3 oz Mionetto Alcohol-Removed Sparkling Wine', '1 oz Fresh Grapefruit Juice', '0.5 oz St-Germain Elderflower Liqueur', '1 dash Angostura Orange Bitters'],
    method: 'Combine grapefruit juice, St-Germain, and bitters in a glass with ice. Top off with the sparkling wine and stir from the bottom.',
    glassware: 'Flute or elegant coupe glass',
  },
  {
    id: '7',
    name: 'The French Sparkler',
    isMocktail: false,
    ingredients: ['titos', 'st_germain', 'cointreau', 'mionetto'],
    spec: ["1 oz Tito's Handmade Vodka", '0.5 oz St-Germain', '0.25 oz Cointreau', '0.5 oz Fresh Lemon Juice', 'Top with Mionetto Sparkling'],
    method: 'Shake vodka, elderflower, triple sec, and lemon juice with ice. Strain into a glass and top with sparkling wine.',
    glassware: 'Champagne flute or coupe with a lemon twist',
  },
  {
    id: '8',
    name: 'Blue Diamond Highball',
    isMocktail: false,
    ingredients: ['titos', 'blue_curacao', 'cointreau'],
    spec: ["1.25 oz Tito's Handmade Vodka", '0.5 oz Blue Curaçao', '0.5 oz Cointreau', '0.75 oz Fresh Lime Juice', 'Top with Club Soda'],
    method: 'Shake the spirits and lime juice together with ice. Strain into a tall glass over cracked ice and fill up with club soda.',
    glassware: 'Collins glass with a lime wheel setup',
  },
  {
    id: '9',
    name: 'The Lychee French 75',
    isMocktail: false,
    ingredients: ['titos', 'lychee_juice', 'st_germain', 'orange_bitters', 'mionetto'],
    spec: ["1.5 oz Tito's Vodka", '1.5 oz Lychee Juice', '0.5 oz St-Germain', '0.5 oz Lemon Juice', '2 dashes Orange Bitters', '2 oz Mionetto 0% Sparkling'],
    method: 'Shake vodka, lychee, St-Germain, lemon, and bitters with ice. Strain into glass and top with sparkling wine.',
    glassware: 'Chilled coupe or flute with lemon twist',
  },
  {
    id: '10',
    name: 'The Lychee & Elderflower Fizz',
    isMocktail: true,
    ingredients: ['lychee_juice', 'st_germain', 'mionetto'],
    spec: ['2 oz 100% Lychee Juice', '0.5 oz St-Germain Elderflower Liqueur', '0.5 oz Fresh Lemon Juice', '2 oz Mionetto Alcohol-Removed Sparkling Wine', '1 oz Club Soda'],
    method: 'Shake lychee juice, St-Germain, and lemon juice with ice. Strain into glass and top with sparkling wine and club soda.',
    glassware: 'Coupe or flute garnished with a lemon wheel',
  }
];
